### ISSUE TITLE
LOTR support.

### ISSUE THREAD

**Issue by MagmaBro123** [GTNewHorizons/AngelicaCompat#1]
Title.

Auto-disable LOTR's sky and cloud config options while shaders are loaded.

See https://lotrminecraftmod.fandom.com/wiki/Resource_Packs/Vibrance_(Chocapic13%27_Shaders_Edit) for more info.

Some glitches are also a thing, but that might be fixable (if you don't mind fucking with LOTR code).

**Comment by Cleptomania** [comment]
Closing as this has an issue on the main Angelica repo
